#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\Index::index

Password:
    path: /test/{temp}
    controller: App\Controller\Index::mdp